spring:
  redis:
    # Redis服务器地址
    host: 47.101.145.187
    # Redis服务器连接端口
    port: 4000
    # Redis服务器连接密码（默认为空）
    password: jokeyou
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
server:
  port: 7070